### PR TITLE
fix cluster detail storage crad can be save as template

### LINKED ISSUE #12: Saving the plug-in card of the cluster details page as a template is not implemented
**Describe the Bug**
Saving the plug-in card of the cluster details page as a template is not implemented

**Versions Used**
Kubernetes:
Kubeclipper:

**Environment**

**Expected behavior**
The cluster details page plug-in card can be saved as a template

### PR DESCRIPTION
**Pull request by lysign**
Signed-off-by: liuying <liu.ying@99cloud.net>

### What type of PR is this?
/kind bug

### Which issue(s) this PR fixes:

Fixes #12 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by moweiwei — COMMENTED** [review]
/lgtm
/approve

File: src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx [hunk 1]
```diff
@@ -161,11 +162,30 @@ function Plugins() {
...
+          item: {
+            component: item,
+            pluginName: name,
+            pluginVersion: version,
+            pluginCategory: category,
+          },
+        };
+
+        const deleteButtonProps = {
           id: 'kubesphere',
```
Comment (moweiwei) [inline src/pages/cluster/containers/Cluster/Detail/Plugins/index.jsx:189]: 开源里 hardcode kubesphere 不太好，之前代码的 hardcode 我在改，这里能不能避免 hardcode

**Review by moweiwei — COMMENTED** [review]
/lgtm
/approve
