### PR TITLE
fix cluster template deletion error

### LINKED ISSUE #6: Cluster template deletion error
**Describe the Bug**
1. Create a plug-in template with the template name and description aligned to the left
2. Error in editing cluster and plug-in templates
3. Error when deleting cluster and plug-in template
plugin-template
edit

delete

**Versions Used**
Kubernetes:
Kubeclipper:

**Environment**

**Expected behavior**
The template can be deleted successfully

### PR DESCRIPTION
**Pull request by lysign**
Change-Id: Ib831d7ea3314a57bdbc4475dd3eb725dc0a29fd0
Signed-off-by: liuying <liu.ying@99cloud.net>

### What type of PR is this?
/kind bug

### Which issue(s) this PR fixes:

Fixes #6 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

File: src/pages/cluster/containers/Template/cluster/actions/Delete.jsx [hunk 1]
```diff
@@ -39,10 +41,33 @@ export default class Delete extends ConfirmAction {
     return t('delete Template');
   }
 
+  getTemplateName = (data) =>
+    isArray(data)
+      ? data.map((it) => it.templateName).join(', ')
+      : data.templateName;
```
Comment (moweiwei) [inline src/pages/cluster/containers/Template/cluster/actions/Delete.jsx:47]: suggest use `getName` func which used in parent class

File: src/pages/cluster/containers/Template/cluster/actions/Delete.jsx [hunk 2]
```diff
@@ -39,10 +41,33 @@ export default class Delete extends ConfirmAction {
...
+
+  submitSuccessMsg = (data) => {
+    const name = this.getTemplateName(data);
+    return firstUpperCase(
+      t('{action} {name} successfully.', {
+        action: this.actionName || this.title,
+        name,
+      })
+    );
+  };
```
Comment (moweiwei) [inline src/pages/cluster/containers/Template/cluster/actions/Delete.jsx:65]: it is unnecessary when use `getName`
